'use client';

import './devices.css';
import { useRouter } from 'next/navigation';
import Desclaimer from '../components/Desclaimer/Desclaimer';

export default function DevicePage() {
  const router = useRouter();

  return (
    <main className="device-page">
      <div className="device-wrap">
        <header className="device-header">
          <div>
            <a href="https://hrv.live" rel="noopener noreferrer">
              HRV.LIVE
            </a>{' '}
            // DEVICES
          </div>

          <div>
            <a href="https://rmssd.com" rel="noopener noreferrer">
              rmssd.com
            </a>
          </div>
        </header>

        <div className="device-kicker">Technical Specifications &amp; Hardware Architecture</div>

        <p className="device-lede">
          The single most critical variable in true Heart Rate Variability analysis is the uncorrupted calculation of individual R-R
          intervals (the exact time in milliseconds between successive heartbeats).
        </p>

        <p>
          If the underlying hardware misses a millisecond, the mathematical reality of your autonomic state is corrupted. Because we do not
          smooth, dampen, or approximate your data,{' '}
          <a href="https://hrv.live/" target="_blank" rel="noopener noreferrer" className="device-inline-link">
            Hrv.live
          </a>{' '}
          enforces strict hardware standards.
        </p>

        <section className="device-section">
          <div className="device-status device-status-gold">
            <span className="device-status-dot" />
            <span>Certified Gold Standard</span>
            <span className="device-status-note">Highly Recommended</span>
          </div>

          <div className="device-card">
            <h2>Polar H10 Chest Strap</h2>

            <p>
              The Polar H10 is universally recognized in clinical and sports science research as the gold standard for portable
              electrocardiogram (ECG) data transmission. It captures raw electrical signals directly from the heart muscle, delivering true
              millisecond accuracy. We confidently rely on the metrics generated by this sensor. The Mayo Clinic, FDNY, and individual NFL
              and MLB teams do as well.
            </p>
          </div>
        </section>

        <section className="device-section">
          <div className="device-status device-status-variable">
            <span className="device-status-dot" />
            <span>Variable Compliance</span>
            <span className="device-status-note">Proceed with Caution</span>
          </div>

          <div className="device-card">
            <h2>Garmin / Wahoo ECG Chest Straps</h2>

            <p>
              While these secondary chest monitors utilize identical electrical tracking principles to measure R-R intervals and may
              interface with our Web Bluetooth API, variations in manufacturer firmware mean we cannot explicitly guarantee uncompromised
              data fidelity over long testing blocks.
            </p>
          </div>
        </section>

        <section className="device-section">
          <div className="device-status device-status-danger">
            <span className="device-status-dot" />
            <span>Non-Compliant</span>
            <span className="device-status-note">Strictly Incompatible</span>
          </div>

          <div className="device-card">
            <h2>Apple Watch, Whoop, Oura, Fitbit</h2>

            <p>
              These devices will not work with our live engine. Consumer wristbands and smart rings do not measure the electrical activity
              of the heart. Instead, they use optical sensors (Photoplethysmography, or PPG) to guess heart activity based on blood volume
              changes under the skin.
            </p>

            <p>
              While optical tracking is fine for estimating historical averages while you sleep, it is fundamentally incapable of capturing
              the immediate, raw millisecond fluctuations required for live, time-domain biofeedback.
            </p>
          </div>
        </section>

        <Desclaimer />
        <div className="return-link">
          RETURN TO{' '}
          <button type="button" onClick={() => router.push('/')} className="return-link-button">
            HRV.LIVE
          </button>{' '}
          DASHBOARD
        </div>
      </div>
    </main>
  );
}
